### PR TITLE
feat(company data): extend legal entity pattern to support all language

### PR DESCRIPTION
**Pull request by typecastcloud**
## Description

The legal entity pattern now supports and uses letter and currency [unicode categories](https://www.regular-expressions.info/unicode.html).
- Add support of unicode categories via /u option.
- This required update of ecma script to version 6.

## Why

International support requires a lot of different languages. Evaluating and reviewing REGEX by using ranges is very hard.

## Issue

Refs: eclipse-tractusx/portal#360
Dep: eclipse-tractusx/portal-backend#1043

## Checklist

- [x] I have performed a self-review of my own code
- [x] I have successfully tested my changes locally
- [x] I have added tests that prove my changes work
- [x] I have checked that new and existing tests pass locally with my changes
- [x] I have commented my code, particularly in hard-to-understand areas

### CODE REVIEW

**Review by ss-nikunj — APPROVED** [review]
lgtm

**Comment by ss-nikunj** [comment]
Hi @typecastcloud, Change log entry is missing.

**Review by shubhamv-ss — APPROVED** [review]
Looks good!

**Comment by ybidois** [comment]
@MaximilianHauer can you please prioritize this, please? This will make sure we don't run into errors when registering some of our existing customers during the Jupiter Go Live.

**Review by evegufy — COMMENTED** [review]
@oyo could you please review?

**Comment by MaximilianHauer** [comment]
fine for me  @oyo's turn ;)

**Review by oyo — APPROVED** [review]
@typecastcloud contribution approved - please resolve merge conflicts

**Review by oyo — CHANGES_REQUESTED** [review]
@typecastcloud conent approved but setting to request changes until merge conflicts resolved

**Comment by typecastcloud** [comment]
> @typecastcloud content approved but setting to request changes until merge conflicts resolved

Rebased and updated dependencies. Thanks!

**Review by oyo — APPROVED** [review]

**Pull request merged**
