### PR TITLE
feat(legal entity): extended legal entity length

### PR DESCRIPTION
**Pull request by typecastcloud**
## Description

Extended pattern with additional currency characters and length adjustment. Tests added.

Min length: 1
Max lenth: 160

Allows " (double quote \x22) to follow back-end implementation.
Allows £$€¥¢ to allow some additional currency symbols that are used in existing companies.

## Why

Much longer company names exist than currently allowed.

Example:
https://find-and-update.company-information.service.gov.uk/company/03249311 
88 characters

## Issue

Refs: eclipse-tractusx/portal#360

## Checklist

- [x] I have followed the [contributing guidelines](https://github.com/eclipse-tractusx/portal-assets/blob/main/docs/developer/Technical%20Documentation/Dev%20Process/How%20to%20contribute.md#commit-and-pr-guidelines)
- [x] I have performed a self-review of my own code
- [x] I have successfully tested my changes locally
- [x] I have added tests that prove my changes work
- [x] I have checked that new and existing tests pass locally with my changes
- [x] I have commented my code, particularly in hard-to-understand areas

### CODE REVIEW

**Comment by jjeroch** [comment]
Looks good. @typecastcloud did you checked once if this also works for BPDM?
Since we are submitting the data to BPDM via the Gate, we should ensure that we dont receive limitations/errors from their side.
I guess all FE are neither validated as well, right? If so, I would directly create a FE ticket to validate the capability of the FE to display the Company everywhere correctly.

**Review by oyo — APPROVED** [review]

**Comment by typecastcloud** [comment]
> Looks good. @typecastcloud did you checked once if this also works for BPDM?
> Since we are submitting the data to BPDM via the Gate, we should ensure that we dont receive limitations/errors from their side.
> I guess all FE are neither validated as well, right? If so, I would directly create a FE ticket to validate the capability of the FE to display the Company everywhere correctly.

There is no limitation in BPDM Gate and Pool regarding the length of company names. We checked this a few weeks ago. @AmirMattarx @nicoprow could you please confirm.

Portal backend needs to be aligned with regex and all frontend elements need to be checked to properly support longer names. I can create a PR in the backend repository.

**Comment by AmirMattarx** [comment]
Regarding the company name , in the DB of course there is limitation since the fields is created with varchar 255 , that means the limit is 255 chars

**Comment by manojava-gk** [comment]
@typecastcloud I got a security hot spot issue for postalCode pattern in another repo

postalCodePattern:
    /^(?!.*\s$)(?=[a-zA-Z\d-]*[-\s]?[a-zA-Z\d-]*$)[a-zA-Z\d\s-]{2,10}$/
    
    That's because it's using '*' so the input can have infinite length which we should always limit. Use something like
 
{0,10} instead of '*'

So final regex - /^(?!.*\s$)(?=[a-zA-Z\d-]{0,10}[-\s]?[a-zA-Z\d-]{0,10}$)[a-zA-Z\d\s-]{2,10}$/

CC - @oyo

**Comment by typecastcloud** [comment]
> @typecastcloud I got a security hot spot issue for postalCode pattern in another repo
> 
> postalCodePattern: /^(?!._\s$)(?=[a-zA-Z\d-]_[-\s]?[a-zA-Z\d-]*$)[a-zA-Z\d\s-]{2,10}$/
> 
> That's because it's using '*' so the input can have infinite length which we should always limit. Use something like
> 
> {0,10} instead of '*'
> 
> So final regex - /^(?!.*\s$)(?=[a-zA-Z\d-]{0,10}[-\s]?[a-zA-Z\d-]{0,10}$)[a-zA-Z\d\s-]{2,10}$/
> 
> CC - @oyo

Hi,
postalCodePattern was not touched in this PR. Can we fix this security finding in a different PR?

**Comment by oyo** [comment]
> Hi, postalCodePattern was not touched in this PR. Can we fix this security finding in a different PR?

okay for me to fix it in a separate PR

**Review by oyo — APPROVED** [review]

**Review by evegufy — APPROVED** [review]

**Pull request merged**
